/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup BetterflowAssets;
extern const Sifteo::PinnedAssetImage WinScreen;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::PinnedAssetImage Earth2Tile;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::PinnedAssetImage Earth1Tile;
extern const Sifteo::PinnedAssetImage Water2Tile;
extern const Sifteo::PinnedAssetImage AirTile;
extern const Sifteo::PinnedAssetImage Water1Tile;
extern const Sifteo::PinnedAssetImage FireTile;
extern const Sifteo::AssetImage BaseCauldron;
extern const Sifteo::AssetImage LevelGoal1;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::PinnedAssetImage Icon;
extern const Sifteo::AssetImage Ingredients[14];
